
draw_set_font(f_normal);
gesture_double_tap_time(.06);
//DEBUG vars
globalvar debug;
debug = false;
checkSum = "NULL";
showMenu = false;

init_data();

ShipNames = ["Spooner", "Frigate", "Dreadnought"];
ShipSprites = [spr_spooner, spr_frigate, spr_dreadnought];
ShipPrices = [2000,4500,7000];

roomCurrent = room;

affiliations = ["Arcadian", "Terran"];
birthplaces = ["Spaceborn", "Earthborn"];
specializations = ["Medic","Mechanic","Engineer","Nurse","Security Guard","Computer Specialist","Scientist","Business Owner", "Accountant","Diplomat","Politician","Doctor","Handyman","Researcher","Soldier","Smuggler"];

maleNames = [	"Jermaine Hanson",
	"Andres Weaver",
	"Jeremiah Barnett",
	"Dallas Morgan",
	"Sherman Jacobs",
	"Willie Tyler",
	"Gordon Rose",
	"Ronald Moody",
	"Leland Mccoy",
	"Jeff Harris",
	"Orville Watts",
	"Danny Chapman",
	"Bruce Rodgers",
	"Tony Terry",
	"Juan Hughes",
	"Jon Willis",
	"Allen Price",
	"Joseph Warner",
	"Alejandro Washington",
	"Shane Cain",
	"Freddie Matthews",
	"Delbert Peterson",
	"Steven Carlson",
	"Harvey Green",
	"Salvatore Reed",
	"Guy Potter",
	"Milton Gonzales",
	"Moses Mcdonald",
	"Garrett Mendoza",
	"Sidney Wallace",
	"Mack Richards",
	"Carlton Curry",
	"Fernando Mcbride",
	"Isaac Ballard",
	"Geoffrey Pena",
	"Edwin Stanley",
	"Brad Sanders",
	"Santiago Phillips",
	"Taylor Harper",
	"Rickey Kennedy",
	"Enrique Jensen",
	"Noah Neal",
	"Roderick Burton",
	"Ignacio Holloway",
	"Cedric Sutton",
	"Lorenzo Lindsey",
	"Rufus Ball",
	"Rudy Williamson",
	"Archie Meyer",
	"Randal Spencer",
	"Tyrone Moran",
	"Seth Burke",
	"Lamar Hogan",
	"Cary Martinez",
	"Antonio Rodriguez",
	"Alexander Rios",
	"Clayton Leonard",
	"Ivan Moore",
	"Homer Massey",
	"Gilberto Mullins",
	"Casey Hansen",
	"Gene Wolfe",
	"Terrence Nguyen",
	"Barry Summers",
	"Jared Hines",
	"Claude Hall",
	"Marcos Baker",
	"Lloyd Doyle",
	"William Colon",
	"Neil Robertson",
	"Rex Daniels",
	"Derek Cunningham",
	"Dominick Waters",
	"Jesus Patrick",
	"Arturo Greene",
	"Pete Wilson",
	"Leslie Carson",
	"Larry Zimmerman",
	"Percy Carter",
	"Luther Obrien",
	"Wallace Webster",
	"Clifton Ray",
	"Evan Black",
	"Dan Edwards",
	"Jay Davidson",
	"Jerome Riley",
	"Lester Perry",
	"Bernard Griffin",
	"Timothy Hamilton",
	"Sergio Gonzalez",
	"Randy Casey",
	"Carlos Floyd",
	"Dennis Taylor",
	"Travis Tucker",
	"Jonathon Douglas",
	"Edward Mckenzie",
	"Ian Thornton",
	"Jack Francis",
	"Gregg Alvarado",
	"Erick Grant"
]

femaleNames = [	 "Kristine Ross",
	 "Rita Gilbert",
	 "Edna Cummings",
	 "Geneva Copeland",
	 "April Mason",
	 "Delia Martinez",
	 "Joyce Christensen",
	 "Ella Freeman",
	 "Shawna Thomas",
	 "Jacqueline Warren",
	 "Dora Adams",
	 "Leona Rodgers",
	 "Jean Reynolds",
	 "Patsy Fletcher",
	 "Bridget Chambers",
	 "Leticia Mathis",
	 "Jamie Long",
	 "Beverly Osborne",
	 "Vicky Soto",
	 "Sherri Schmidt",
	 "Christine Phillips",
	 "Brandi Cain",
	 "Jody Watson",
	 "Angelina Patton",
	 "Misty Myers",
	 "Wendy Murray",
	 "Sheri Wood",
	 "Jill Davidson",
	 "Belinda Dean",
	 "Marjorie Obrien",
	 "Maxine Hodges",
	 "Brooke Newton",
	 "Thelma Brock",
	 "Patricia Abbott",
	 "Traci Lambert",
	 "Blanche Kim",
	 "Robyn Munoz",
	 "Tonya Russell",
	 "Joy Gomez",
	 "Alice Fowler",
	 "Constance Hoffman",
	 "Nina Williams",
	 "Julie Lynch",
	 "Jodi Goodman",
	 "Gina Taylor",
	 "Erika Williamson",
	 "Jessica Moran",
	 "Tiffany Jackson",
	 "Pamela Hanson",
	 "Alison Cole",
	 "Minnie Young",
	 "Lynda Walters",
	 "Pam Townsend",
	 "Ernestine May",
	 "Hannah Ortiz",
	 "Bethany Miles",
	 "Genevieve Wilkins",
	 "Lee Brooks",
	 "Nellie Fox",
	 "Marguerite Perry",
	 "Margie Jacobs",
	 "Jenny Peterson",
	 "Mary Norton",
	 "Karla Banks",
	 "Elisa Fitzgerald",
	 "Lela Mcdonald",
	 "Janis Barnett",
	 "Sheila Page",
	 "Ginger Frazier",
	 "Kellie Bryant",
	 "Marlene Rivera",
	 "Krystal Poole",
	 "Cecilia Fleming",
	 "Amber Salazar",
	 "Jackie Bowman",
	 "Heather Buchanan",
	 "Bessie Bailey",
	 "Carolyn Howard",
	 "Tamara Weber",
	 "Jennifer Henry",
	 "Ruth Ramsey",
	 "Eleanor Walton",
	 "Dianna Delgado",
	 "Stacy Howell",
	 "Jeannie Davis",
	 "Ana Luna",
	 "Grace Spencer",
	 "Adrienne Nelson",
	 "Dorothy Mccormick",
	 "Amy Foster",
	 "Henrietta Watkins",
	 "Charlene Terry",
	 "Melody Clayton",
	 "Carrie Sims",
	 "Roxanne Houston",
	 "Sophie Greer",
	 "Lisa Warner",
	 "Bertha Perez",
	 "Laura Curry",
	 "Sonia Jones",
]