uiFont = f_menu;
if file_exists("savedata.ini") {
	uiTextColor = $05DF37;
	uiControlName = "loadgame";
} else {
	uiTextColor = $4D4D4D;
	uiControlName = "noloaddata";
}
uiTextValue = "Continue";
//uiButtonSprite = spr_newGameBtn;
uiSetWidth = 200;
//uiSetHeight = sprite_get_height(uiButtonSprite);
//uiSpriteScale = 10;
uiDrawBackColor = false;
uiBackColor = c_black;
uiEventObject = obj_gameMenu;
uiMoveX = room_width/8;
uiAniMove = true;
uiHoverColor = c_white;
